---

- block:
    - name: Extract local plugins dir
      shell: "check_mk_agent | grep 'LocalDirectory' | awk {'print $2'}"
      changed_when: false
      register: read_LocalDirectory_search_result
      args:
        warn: no

    - name: Set var with local plugins dir
      set_fact:
        check_mk_agent_steal_time_local_dir: "{{ read_LocalDirectory_search_result.stdout_lines[0] }}"

    - name: Extract check_mk_agent config dir
      shell: "check_mk_agent | grep 'AgentDirectory' | awk {'print $2'}"
      changed_when: false
      register: read_AgentDirectory_search_result
      args:
        warn: no

    - name: Set var with  check_mk_agent config dir
      set_fact:
        check_mk_agent_steal_time_config_dir: "{{ read_AgentDirectory_search_result.stdout_lines[0] }}"

    - name: Check if configuration file exists
      stat:
        path: "{{ check_mk_agent_steal_time_config_dir }}/mrpe.cfg"
      register: read_check_mk_agent_config_file_result

  tags:
    - role::check_mk_agent_steal_time
    - role::check_mk_agent_steal_time::configuration
