---
# Role tasks
- include_role:
    name: amtega.check_platform
  vars:
    check_platform_distributions:
      centos: 7
      rhel: 7

- block:
    - import_tasks: check_configuration.yml
    - import_tasks: install.yml
  tags:
    role::check_mk_agent_steal_time
