---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
    requirements-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
driver:
  name: docker
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: centos:7
    dockerfile: Dockerfile.systemd.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: centos:8
    dockerfile: Dockerfile.systemd.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
  - name: "fedora33-${INSTANCE_UUID:-1}"
    image: fedora:33
    dockerfile: Dockerfile.systemd.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_33
  - name: "fedora34-${INSTANCE_UUID:-1}"
    image: fedora:34
    dockerfile: Dockerfile.systemd.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_34
provisioner:
  name: ansible
  ansible_args:
    - --inventory=${ANSIBLE_INVENTORY}
    - --vault-password-file=${ANSIBLE_VAULT_PASSWORD_FILE:-/etc/hostname}
  config_options:
    defaults:
      callback_enabled: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          ansible_user: root
          check_mk_agent_autojoin: no
      molecule_hosts_centos_8:
        vars:
          check_mk_agent_version: 1.6.0p15
          check_mk_agent_artifact:
            id: check_mk_agent_artifact
            type: gitlab
            host: https://gitlab-sistemas.xunta.local
            project: ansible/dml
            branch: master
            path: /checkmk
            file: check-mk-agent-{{ check_mk_agent_version }}-1.noarch.rpm
            dest: /tmp
            username: "{{ grp_all_ansible_user }}"
            password: "{{ grp_all_ansible_gitlab_token | string }}"
            validate_certs: no
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
      molecule_hosts_fedora_33:
        vars:
          check_mk_agent_version: 1.6.0p15
          check_mk_agent_artifact:
            id: check_mk_agent_artifact
            type: gitlab
            host: https://gitlab-sistemas.xunta.local
            project: ansible/dml
            branch: master
            path: /checkmk
            file: check-mk-agent-{{ check_mk_agent_version }}-1.noarch.rpm
            dest: /tmp
            username: "{{ grp_all_ansible_user }}"
            password: "{{ grp_all_ansible_gitlab_token | string }}"
            validate_certs: no
      molecule_hosts_fedora_34:
        vars:
          check_mk_agent_version: 1.6.0p15
          check_mk_agent_artifact:
            id: check_mk_agent_artifact
            type: gitlab
            host: https://gitlab-sistemas.xunta.local
            project: ansible/dml
            branch: master
            path: /checkmk
            file: check-mk-agent-{{ check_mk_agent_version }}-1.noarch.rpm
            dest: /tmp
            username: "{{ grp_all_ansible_user }}"
            password: "{{ grp_all_ansible_gitlab_token | string }}"
            validate_certs: no
verifier:
  name: ansible
